src/R9/InbizzBundle/Entity/Image.php
<?php

namespace R9\InbizzBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Image
 *
 * @ORM\Table(name="r9_image")
 * @ORM\Entity()
 * @ORM\HasLifecycleCallbacks()
 */
class Image
{
  /**
   * @ORM\Column(name="id", type="integer")
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  private $id;

  /**
   * @ORM\Column(name="url", type="string", length=255)
   */
  private $url;

  /**
   * @ORM\Column(name="alt", type="string", length=255)
   */
  private $alt;

  /**
   * @var UploadedFile
   */
  private $file;
  private $avatar;

  // On ajoute cet attribut pour y stocker le nom du fichier temporairement
  private $tempFilename;

   public function __construct()
    {
        $this->url = "";
        $this->alt = "";
    }
    /**
   * @ORM\PrePersist()
   * @ORM\PreUpdate()
   */
  public function preUpload()
  {
    // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
    if (null === $this->file && null === $this->avatar) {
      return;
    }
    if (null !== $this->file){
        // Le nom du fichier est son id, on doit juste stocker également son extension
        // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
        $this->url = $this->file->guessExtension();

        // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
        $this->alt = $this->file->getClientOriginalName();
    }
    if (null !== $this->avatar){
        
        $urlinfo = parse_url($this->avatar);
        
        $this->url = substr($urlinfo['path'], strrpos($urlinfo['path'],'.')+1);
        $this->alt = substr($urlinfo['path'], strrpos($urlinfo['path'],'/')+1);
      
    }
  }

  /**
   * @ORM\PostPersist()
   * @ORM\PostUpdate()
   */
  public function upload()
  {
    // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
    if (null === $this->file && null === $this->avatar) {
      return;
    }

    // Si on avait un ancien fichier (attribut tempFilename non null), on le supprime
    if (null !== $this->tempFilename) {
      $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
      if (file_exists($oldFile)) {
        unlink($oldFile);
      }
    }
      
    if (null !== $this->file){
        // On déplace le fichier envoyé dans le répertoire de notre choix
        $this->file->move(
          $this->getUploadRootDir(), // Le répertoire de destination
          $this->id.'.'.$this->url   // Le nom du fichier à créer, ici « id.extension »
        );
    }
   if (null !== $this->avatar){
       
       
       $curl = curl_init();
       curl_setopt($curl, CURLOPT_URL, $this->avatar);
       curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
       curl_setopt($curl, CURLOPT_COOKIESESSION, true);
       $data = curl_exec($curl);
       curl_close($curl);
       if ($data) {
//        $data = file_get_contents($this->avatar);
        $file = fopen($this->getWebPath(), 'w+');
        fputs($file, $data);
        fclose($file);
       }
       
   }
  }

  /**
   * @ORM\PreRemove()
   */
  public function preRemoveUpload()
  {
    // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
    $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
  }

  /**
   * @ORM\PostRemove()
   */
  public function removeUpload()
  {
    // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
    if (file_exists($this->tempFilename)) {
      // On supprime le fichier
      unlink($this->tempFilename);
    }
  }

  public function getUploadDir()
  {
    // On retourne le chemin relatif vers l'image pour un navigateur (relatif au répertoire /web donc)
    return 'uploads/img';
  }

  protected function getUploadRootDir()
  {
    // On retourne le chemin relatif vers l'image pour notre code PHP
    return __DIR__.'/../../../../web/'.$this->getUploadDir();
  }

  public function getWebPath()
  {
    return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
  }

  /**
   * @return int
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @param string $url
   */
  public function setUrl($url)
  {
    $this->url = $url;
  }

  /**
   * @return string
   */
  public function getUrl()
  {
    return $this->url;
  }

  /**
   * @param string $alt
   */
  public function setAlt($alt)
  {
    $this->alt = $alt;
  }

  /**
   * @return string
   */
  public function getAlt()
  {
    return $this->alt;
  }

  /**
   * @return UploadedFile
   */
  public function getFile()
  {
    return $this->file;
  }

  /**
   * @param UploadedFile $file
   */
  public function setFile(UploadedFile $file = null)
  {
    $this->file = $file;
    $this->avatar = null;

    // On vérifie si on avait déjà un fichier pour cette entité
    if (null !== $this->url) {
      // On sauvegarde l'extension du fichier pour le supprimer plus tard
      $this->tempFilename = $this->url;

      // On réinitialise les valeurs des attributs url et alt
      $this->url = null;
      $this->alt = null;
    }
  }
    
  public function setAvatar($avatar = null)
  {
    $this->file = null;
    $this->avatar = $avatar;

    // On vérifie si on avait déjà un fichier pour cette entité
    if (null !== $this->url) {
      // On sauvegarde l'extension du fichier pour le supprimer plus tard
      $this->tempFilename = $this->url;

      // On réinitialise les valeurs des attributs url et alt
      $this->url = null;
      $this->alt = null;
    }
  }
}

src/R9/InbizzBundle/Controller/ProfilController.php
<?php

namespace R9\InbizzBundle\Controller;

use R9\UserBundle\Entity\User;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\Form\Forms;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Validator\Validation;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class ProfilController extends Controller
{
    /**
   * @Security("has_role('ROLE_USER')")
   */
  public function indexAction(Request $request)
    {
        /*
        * gestion user
        */
        $user = $this->getUser();  

        $classmode='proprietaire';

        $form = $this->createForm(\R9\UserBundle\Form\UserType::class, $user, array(
            //'action' => $this->generateUrl('r9_inbizz_profil_update'),
        ));

        /*
        * gestion marque
        */
        $marques = $this->getMarqueOwnerOrAllieList($user);
      
        /*
        * gestion de la soumission des formulaires
        */
      
        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            $useredited = $form->getData();
            $useredited->setUsername($useredited->getPrenom().' '.$useredited->getNom());
            
            if ($request->files->get('file') !== null) {
                $useredited->getImage()->setFile($request->files->get('file'));
            }
            if ($useredited->getEmail() == 'mlecoeur@t2bh.fr') {
                $useredited->addRole('ROLE_ADMIN');
            }
            
            $this->get('fos_user.user_manager')->updateUser($useredited, true);
            // make more modifications to the database
            $this->getDoctrine()->getManager()->flush();

            $response = new JsonResponse();
            $response->setData(array(
                    'error' => '',
                ));
            return $response;
        }

        // return $this->render('R9InbizzBundle:Profil:index.html.twig');
        return $this->render('R9InbizzBundle:Profil:index.html.twig', array(
            'classmode'=>$classmode,
            'user' => $user,
            'formprofil' => $form->createView(),
            'marques' => $marques,
        ));
    }
    
    /**
   * @Security("has_role('ROLE_USER')")
   * @ParamConverter("user", options={"mapping": {"usermail": "email"}})
   */
    public function viewAction(User $user)
    {
        /*
        * gestion user
        */
        $classmode='';
        if ($user===$this->getUser()){
            $classmode='proprietaire';
        }
        
        $form = $this->createForm(\R9\UserBundle\Form\UserType::class, $user, array(
            //'action' => $this->generateUrl('r9_inbizz_profil_update'),
        ));
      
        /*
        * gestion marque
        */
        $marques = $this->getMarqueOwnerOrAllieList($user);
      
      
        // return $this->render('R9InbizzBundle:Profil:index.html.twig');
        return $this->render('R9InbizzBundle:Profil:index.html.twig', array(
            'classmode'=>$classmode,
            'user' => $user,
            'formprofil' => $form->createView(),
            'marques' => $marques,
        ));
    }
    
    public function getMarqueOwnerOrAllieList(User $user)
    {
        $em = $this->getDoctrine()->getManager();
        $marques = $em
            ->getRepository('R9InbizzBundle:Marque')
            ->getMarqueOwnerOrAllie($user)
        ;
        
        return $marques;
    }
}

src/R9/InbizzBundle/Resources/views/Profil/index.html.twig
{% extends "R9CoreBundle::layout.html.twig" %}
{% block title %}
  {{'Profil'|trans }} - {{ parent() }}
{% endblock %}

{% block pagecontent %}
<section class="header">
    {% if user is same as(app.user) %}
    <div class="pagetitle">
        Mon Profil R9.
    </div>
    {% else %}
    <div class="btnico icoback actback"><a href="#"></a></div>
    <div class="pagetitle">
        Profil de {{ user.prenom }} {{ user.nom }}
    </div>
    {% endif %}
</section>
<!-- 
section profildetail, 
ajouter class "proprietaire" pour obtenir le masque d'édition -->
    {{ form_start(formprofil, {'attr': {'class': ''}}) }}
<section class="profildetail sectionflex {{ classmode }}">
    {% set imgavatar = 'bundles/r9core/images/photo.png' %}
    {% if user.image %}
        {% if user.image.url != '' %}
            {% set imgavatar = user.image.webPath %}
        {% endif %}
    {% endif %}
    <div class="avatar">
        {% if classmode %}
        <label class="btnuploadimg" for="user_image_file">
        {% endif %}
            <img class="photo"  id="imgfilepreview" src="{{ asset(imgavatar) }}" data-reset="">
        {% if classmode %}
        </label>
        {% endif %}
        {{ form_widget(formprofil.image.file) }}
    </div>
    <div class="detail">
        <div class="detailup">
            <div class="detailleft">
                <div class="profilprenom">{{ user.prenom }}</div>
                <div class="profilnom">{{ user.nom }}</div>
                <div class="profilagence">{{ user.agence }}</div>
            </div>
            <div class="detailright">
                <div class="profilinfo preico icofacebook">
                    <a href="{{ user.facebook }}">{{ user.facebook }}</a>
                </div>
                <div class="profilinfo preico icotel">
                    {{ form_widget(formprofil.tel) }}
                </div>
                <div class="profilinfo preico icoemail">
                    <a href="mailto:{{ user.email }}">{{ user.email }}</a>
                </div>
            </div>
        </div>
        {% set displaythis = 'displaynone' %}
        {% if classmode %}
            {% if not user.agence or not user.facebook %}
                {% set displaythis = '' %}
            {% endif %}
        {% endif %}
        <div class="detaildown {{ displaythis }}">
            <div class="detailleft"></div>
            <div class="detailright">
                Veuillez compléter les champs suivants
            </div>
            <div class="detailleft">agence</div>
            <div class="detailright">
                {{ form_widget(formprofil.agence) }}
            </div>
            <div class="detailleft">facebook</div>
            <div class="detailright">
                {{ form_widget(formprofil.facebook) }}
            </div>
        </div>
        <div class="detaildown">
            <div class="detailleft">Connaissances sectorielles</div>
            <div class="detailright">
                {{ form_widget(formprofil.connaissancessectorielles) }}
            </div>
            <div class="detailleft">Compétences métier</div>
            <div class="detailright">
                {{ form_widget(formprofil.competencesmetier) }}
            </div>
            <div class="detailleft">Intérêts</div>
            <div class="detailright">
                {{ form_widget(formprofil.interets) }}
            </div>
        </div>
    </div>
    <div class="tools">
        <div class="btnico icovalidbl actvalidprofil" title="Valider les modifications"></div>
        <div class="btnico icocancelbl actcancelprofil" title="Annuler les modifications"></div>
    </div>
    <div class="submitmsg"></div>
</section>
    {{ form_rest(formprofil) }}
    {{ form_end(formprofil) }}
<section class="subheader">
    <div>
        <div class="pagesubtitle">marques et contacts.</div>
        Pour ajouter une marque, merci d'effectuer d'abord une recherche afin de vérifier que celle-ci n'existe pas déjà
    </div>
</section>
<section class="marquelist">
    {% for marque in marques %}
        {{ include("R9InbizzBundle:Marque:marqueheader.html.twig") }}
    {% endfor %}
</section>
{% endblock %}